name: AuctionHouseX
version: 1.0.3
api-version: 1.13
depend: [Vault]
author: MrMarshall
website: https://mrmarshall.dev/
main: dev.mrmarshall.auctionhousex.AuctionHouseX

commands:
  xpbottle:
    description: Converts player EXP to a physical item
  auctionhouse:
    aliases: [ah]
    description: Opens the Auctionhouse