item-show:
  format: "%prefix%&f%player% %suffix%&f: &f%message%"
auction:
  listingPrice: 0.0
  listingRate: 0.0
  listingDuration: 7d0h0m
  expiredDuration: 14d0h0m
  unclaimedDuration: 90d0h0m
  cleanupDuration: 0d24h0m
  soldDuration: 365d0h0m
  preventCreative: true
  preventSpectator: true
  maxSellPrice: 1000000.00
  salesTax: "0%"
  allowDamagedItems: false
  defaultMaxListings: 45
  # Available sorting orders: oldest | newest
  sortOrder: 'oldest'
  announce: true
blacklist:
  - "bedrock"
  - "barrier"
  - "command_block"
  - "structure_block"
disabled-worlds: []